# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-28 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_auto_20160616_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiado',
            name='estado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
