# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-30 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_filiado_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filiado',
            name='data_filiacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filiado',
            name='data_nascimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
