# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-15 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Associado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=4, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=10)),
                ('situacao', models.CharField(default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Contribuicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('associado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importa.Associado')),
            ],
        ),
    ]
