# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-16 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribuicao',
            name='associado',
        ),
        migrations.DeleteModel(
            name='Associado',
        ),
    ]
